# List of data structures

1	Data types

1.1	Primitive types

1.2	Composite types or non-primitive type

1.3	Abstract data types

2	Linear data structures

2.1	Arrays

2.2	Lists

3	Trees

3.1	Binary trees

3.2	B-trees

3.3	Heaps

3.4	Trees

3.5	Multiway trees

3.6	Space-partitioning trees

3.7	Application-specific trees

4	Hash-based structures

5	Graphs

6	Other

### 2.2 Tuples

##### Ref: https://docs.python.org/3/tutorial/datastructures.html

Though tuples may seem similar to lists, they are often used in different situations and for different purposes. Tuples are immutable, and usually contain a heterogeneous sequence of elements that are accessed via unpacking or indexing (or even by attribute in the case of namedtuples). Lists are mutable, and their elements are usually homogeneous and are accessed by iterating over the list.

In [1]:
# declaration of tupple
t = ()

In [2]:
t =  12345, 54321, 'hello!'

In [3]:
t

(12345, 54321, 'hello!')

The statement t = 12345, 54321, 'hello!' is an example of tuple packing. 

In [4]:
# The reverse operation is also possible
x, y, z = t

In [5]:
x

12345

In [6]:
y

54321

In [7]:
z

'hello!'

This is called, appropriately enough, sequence unpacking and works for any sequence on the right-hand side.

### 2.3 Sets

Curly braces or the set() function can be used to create sets.

In [13]:
# declaration
s = set('arbcd')
s

{'a', 'b', 'c', 'd', 'r'}

In [12]:
# Or
s1 = {'a', 'r', 'b', 'c', 'd'}
s1

{'a', 'b', 'c', 'd', 'r'}

### 2.4 Dictionaries

In [14]:
# Declaration
d = {}
d

{}

In [15]:
# Or
d1 = {'a': 1, 'b': 2}
d1

{'a': 1, 'b': 2}

In [20]:
# Retrieving the value
d1['a']

1

In [22]:
d1['b']

2

##### conditional and loops statements

In [24]:
x = int(input('Enter first value: '))
y = int(input('Enter second value: '))
if(x>y):
    print('First value is big')
else:
    print('Second value is big')

Enter first value: 4
Enter second value: 6
Second value is big


In [27]:
a = int(input('Enter first value: '))
b = int(input('Enter second value: '))
if(a>b):
    print('First value is big')
elif(b>a):
    print('Second value is big')
else:
    print('Both are eqaul')

Enter first value: 2
Enter second value: 2
Both are eqaul


In [29]:
# while loop
n = int(input('How many numbers you want to print: '))
while(n>0):
    print(n)
    n-=1

How many numbers you want to print: 5
5
4
3
2
1


In [30]:
# for loop
n = int(input('How many numbers you want to print: '))
for i in range(n):
    print(i)

How many numbers you want to print: 5
0
1
2
3
4


In [31]:
for i in range(1,n+1):
    print(i)

1
2
3
4
5


#### IN operator which is oftenly used in loops, list, dictionary etc

In [32]:
# Lucky number game like lottry
a = [1,3,6,4,0,9]
luck = int(input('Choose the lucky number for lottery between 1 to 10: '))
if luck in a:
    print('You win the lottery')
else:
    print('Looser')

Choose the lucky number for lottery between 1 to 10: 5
Looser


In [33]:
a = [1,3,6,4,0,9]
luck = int(input('Choose the lucky number for lottery between 1 to 10: '))
if luck in a:
    print('You win the lottery')
else:
    print('Looser')

Choose the lucky number for lottery between 1 to 10: 4
You win the lottery


#### Some useful mathematical oprations

In [34]:
# square
9**2

81

In [35]:
# cube
5**3

125

In [36]:
# square root
3**(1/2)

1.7320508075688772

In [38]:
# cube root
27**(1/3)

3.0